openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.digitalraygun.com
paths:
  /dns/entries?api=v1:
    get:
      responses:
        '200':
          description: OK