apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: azure-subscription-id
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    name: {{ .Values.keyVault.name }}
    object:
      name: azure-subscription-id
      type: secret
---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: azure-resource-group
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    name: {{ .Values.keyVault.name }}
    object:
      name: azure-resource-group
      type: secret
---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: azure-dns-zone
  namespace: {{ .Release.Namespace }}
spec:
  vault:
    name: {{ .Values.keyVault.name }}
    object:
      name: azure-dns-zone
      type: secret