apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.podIdentity.name }}
  namespace: {{ .Release.Namespace }}
spec:
  azureIdentity: {{ .Values.podIdentity.name }}
  selector: {{ .Values.podIdentity.name }}
