#apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
#kind: SecretProviderClass
#metadata:
  #name: drgapi-keyvault
  #namespace: api
#spec:
  #provider: azure
  #secretObjects:
  #- data: 
    #- objectName: azure-subscription-id
      #key: azure-subscription-id
    #secretName: azure-subscription-id
    #type: Opaque
  #parameters:
    #usePodIdentity: "true"
    #keyvaultName: {{ .Values.keyVault.name }}
    #objects:  |
      #array:
        #- |
          #objectName: azure-subscription-id
          #objectType: secret
        #- |
          #objectName: azure-dns-zone
          #objectType: secret
        #- |
          #objectName: azure-resource-group
          #objectType: secret
    #tenantId: {{ .Values.keyVault.tenantId }}